# [http]
# proxy = "127.0.0.1:6152"

# [https]
# proxy = "127.0.0.1:6152"

# ----------------------------------------
#
# 解决Rust -- update crates.io过慢的问题
# https://course.rs/first-try/slowly-downloading.html#%E5%AD%97%E8%8A%82%E8%B7%B3%E5%8A%A8

[source.crates-io]
replace-with = 'rsproxy'

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

# 稀疏索引，要求 cargo >= 1.68
[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"

[net]
git-fetch-with-cli = true
