#!/usr/bin/env just --justfile
# https://just.systems/

set shell := ['fish', '-c']
set dotenv-load := true

# List all available recipes
default:
    @just --list

# Update all components (dotfiles, brew, shells, apps, editors, dev tools, AI tools)
all: update-dotfiles update-brew update-shells update-apps update-editors update-dev update-ai

# Pull latest changes and update submodules
update-dotfiles: pull-latest update-submodules

# Update fish shell plugins and completions
update-shells: update-fish

# Update nvim, vscode, and yazi plugins
update-editors: update-nvim update-vscode update-yazi

# Update R packages, conda, asdf plugins, and rust toolchain
update-dev: update-r-packages update-conda update-asdf update-rust

# Update claude, antigravity, and dws CLI tools
update-ai: update-claude update-antigravity update-dws

# Wash macOS provenance attributes from the project root
wash-macos-provenance:
    # Washing macOS provenance attributes from project root
    wash-macos-provenance {{ justfile_directory() }}

# Pull latest changes from remote repository
pull-latest:
    # Pulling latest changes
    git pull
    @echo

# Pull all changes for the submodules
update-submodules:
    # Pull all changes for the submodules
    git submodule update --remote
    # Record submodule SHAs for review
    git submodule status | awk '{print $1, $2}' > .submodule-versions
    git add .submodule-versions
    @echo "Run 'git diff --cached .submodule-versions' to review, then commit"

# Update fish plugins and generate completions
update-fish:
    # Updating fish plugins
    fisher update
    fish_update_completions
    @echo

# Update asdf plugin repositories and check tool versions
update-asdf:
    # Updating asdf plugin repositories
    asdf plugin update --all
    {{ justfile_directory() }}/asdf/check-tools-version.nu
    @echo

# Update R packages (without prompting)
update-r-packages:
    # Updating R packages
    Rscript -e 'update.packages(ask = FALSE)'
    @echo

# Update Anaconda conda package manager, all packages, and cleanup
update-conda:
    # Update the conda package manager
    conda update -y -n base conda
    # Update all packages in base environment
    conda update --all -y
    # Clean up caches, tarballs, and unused packages
    conda clean --all -y
    # Refresh base environment snapshot for reproducibility
    conda env export -n base --no-builds > {{ justfile_directory() }}/anaconda/base-environment.yml
    @echo

# Update vscode extensions and export list to file
update-vscode:
    # Update vscode extensions
    code --update-extensions
    # Export extension list to file
    code --list-extensions > {{ justfile_directory() }}/backups/vscode/vscode-extensions.txt
    @echo

# Update Homebrew packages and casks according to global Brewfile, then cleanup
update-brew:
    # Update Homebrew formula lists
    brew update
    # Install/upgrade packages according to Brewfile
    brew bundle --global -v
    # Remove packages not in Brewfile
    brew bundle cleanup --global --force
    # Remove unused dependencies
    brew autoremove
    # Clean up old versions and cache
    brew cleanup
    @echo

# Dump current Homebrew packages to global Brewfile
dump-brew:
    #!/usr/bin/env fish
    # Dumping Brewfile
    brew bundle dump --global --force --no-vscode --no-go --no-cargo --no-mas
    # Prepend auto-generated comment to Brewfile
    set -l brewfile {{ justfile_directory() }}/brew/.Brewfile
    set -l tmp $brewfile.tmp
    echo "# AUTO-GENERATED by `just dump-brew`. Do not edit manually." > $tmp
    cat $brewfile >> $tmp
    mv $tmp $brewfile

# Update rustup, rust toolchain, and cargo packages
update-rust:
    # Keeping rustup up to date
    rustup self update
    @echo

    # Keeping rust up to date
    rustup update
    @echo

    # Keeping rust packages up to date.
    cargo install-update -a
    @echo

# Install cargo packages from crates.txt manifest (for new machine setup)
install-cargo-crates:
    # Installing cargo packages from manifest
    grep -v '^#' {{ justfile_directory() }}/rust/.cargo/crates.txt | grep -v '^$$' | xargs -I {} cargo install {}
    @echo

# Install a cargo package and sync it to crates.txt
cargo-install pkg:
    # Installing cargo package: {{ pkg }}
    cargo install {{ pkg }}
    # Append package to crates.txt if not already present
    grep -qx '{{ pkg }}' {{ justfile_directory() }}/rust/.cargo/crates.txt || echo '{{ pkg }}' >> {{ justfile_directory() }}/rust/.cargo/crates.txt
    @echo

# Update AstroNvim and Mason packages
update-nvim:
    #!/usr/bin/env fish
    # Updating AstroNvim (skipped if nvim is not installed)
    if command -v nvim >/dev/null 2>&1
    nvim --headless "+AstroUpdate" "+MasonToolsUpdateSync" "+qa!" 2>&1 || echo "nvim/AstroNvim update failed (non-fatal)"
    else
    echo "nvim not installed; skipping"
    end

# Check outdated applications from App Store
update-apps:
    #!/usr/bin/env fish
    # Checking outdated applications from AppStore
    if test (uname) = Darwin
    mas outdated || true
    mas upgrade || echo "mas upgrade failed or nothing to update"
    else
    echo "App Store updates are macOS-only; skipping"
    end

# Update yazi plugins
update-yazi:
    # Update yazi plugins
    ya pkg upgrade
    @echo

# Update claude CLI
update-claude:
    # Update claude
    claude update
    @echo

# Update DingTalk Workspace CLI (dws)
update-dws:
    # Update DingTalk Workspace CLI (dws)
    dws upgrade -y
    @echo

# Update Antigravity CLI
update-antigravity:
    # Update Antigravity CLI
    agy update
    @echo
