[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    # guifont = "SauceCodePro Nerd Font Mono:h11"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    # defx filemanager
    filemanager = "defx"
    enable_vimfiler_filetypeicon = true
    enable_vimfiler_gitstatus = true
    filetree_direction = "left"
    #autocomplete_method = "coc"
    # automatic_update = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

[[layers]]
name = 'core'
filetree_show_hidden = true

[[layers]]
name = "default"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
autocomplete_method = "coc"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = "colorscheme"

# use "denite" instead
#
# [[layers]]
# name = "fzf"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "denite" 

[[layers]]
name = "debug"

# disable "ctrlspace" due to conflicts with tabline
# [[layers]]
# name = "ctrlspace"
# enable-spacevim-styled-keys = true

[[layers]]
name = "lang#go"

[[layers]]
name = "VersionControl"

[[layers]]
name = "checkers"

[[layers]]
name = "git"
git-plugin = "fugitive"

[[layers]]
name = "github"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "lang#lua"

[[layers]]
name = "format"

[[layers]]
name = "lang#asciidoc"

[[layers]]
name = "lang#autohotkey"

[[layers]]
name = "lang#kotlin"

[[layers]]
name = "lang#r"

[[layers]]
name = "lang#ruby"

[[layers]]
name = "lang#swift"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "tmux"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#julia"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#vim"

[[layers]]
name = "lsp"

[[layers]]
name = "tags"

[[layers]]
name = "tools"

[[layers]]
name = "ui"

[[layers]]
name = "lang#toml"
