name: base
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
dependencies:
  - _anaconda_depends=2026.07
  - aiobotocore=3.7.0
  - aiodns=3.6.1
  - aiohappyeyeballs=2.6.2
  - aiohttp=3.14.1
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - alabaster=1.0.0
  - altair=6.0.0
  - anaconda-anon-usage=0.8.1
  - anaconda-auth=0.15.1
  - anaconda-catalogs=0.2.0
  - anaconda-cli-base=0.9.1
  - anaconda-client=1.14.1
  - anaconda-navigator=2.7.1
  - anaconda-project=0.13.2
  - annotated-doc=0.0.4
  - annotated-types=0.7.0
  - anyio=4.12.1
  - aom=3.13.2
  - applaunchservices=0.3.0
  - appnope=0.1.4
  - appscript=1.4.0
  - archspec=0.2.6
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - arrow-cpp=23.0.1
  - astroid=4.0.3
  - astropy=8.0.1
  - astropy-iers-data=0.2026.7.13.0.54.2
  - asttokens=3.0.1
  - async-lru=2.3.0
  - asyncssh=2.21.1
  - attrs=26.1.0
  - autopep8=2.0.4
  - aws-c-auth=0.10.1
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.2
  - aws-c-event-stream=0.6.1
  - aws-c-http=0.10.13
  - aws-c-io=0.26.3
  - aws-c-mqtt=0.15.2
  - aws-c-s3=0.12.0
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.10
  - aws-crt-cpp=0.37.4
  - aws-sdk-cpp=1.11.774
  - babel=2.17.0
  - backports.zstd=1.3.0
  - bcrypt=5.0.0
  - beautifulsoup4=4.15.0
  - binaryornot=0.6.0
  - black=26.5.1
  - blas=1.0
  - bleach=6.4.0
  - blinker=1.9.0
  - blosc=1.21.6
  - bokeh=3.9.1
  - boltons=25.0.0
  - botocore=1.43.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.7
  - c-blosc2=2.22.0
  - ca-certificates=2026.7.16
  - cachetools=6.2.2
  - cairo=1.18.4
  - cattrs=26.1.0
  - cctools=1030.6.3
  - certifi=2026.6.17
  - cffi=2.1.0
  - chardet=5.2.0
  - charset-normalizer=3.4.7
  - click=8.4.1
  - cloudpickle=3.1.2
  - colorcet=3.2.1
  - comm=0.2.3
  - conda=26.5.3
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-build=26.5.0
  - conda-content-trust=0.3.2
  - conda-index=0.12.1
  - conda-libmamba-solver=26.7.0
  - conda-lockfiles=0.2.1
  - conda-pack=0.9.1
  - conda-package-handling=2.5.0
  - conda-package-streaming=0.13.0
  - conda-pypi=0.11.0
  - conda-rattler-solver=0.1.1
  - conda-repo-cli=1.0.173
  - conda-self=0.2.1
  - contourpy=1.3.3
  - cookiecutter=2.7.1
  - cpp-expected=1.1.0
  - cryptography=49.0.0
  - curl=8.21.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dask=2026.7.1
  - dask-core=2026.7.1
  - datashader=0.19.1
  - dav1d=1.5.3
  - debugpy=1.8.21
  - decorator=5.3.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.4.1
  - distributed=2026.7.1
  - distro=1.9.0
  - dmglib=0.9.5
  - docstring-to-markdown=0.17
  - docutils=0.21.2
  - entrypoints=0.4
  - et_xmlfile=2.0.0
  - evalidate=2.1.4
  - executing=2.2.1
  - expat=2.8.2
  - filelock=3.29.4
  - flake8=7.1.1
  - flask=3.1.3
  - fmt=12.1.0
  - fontconfig=2.17.1
  - fonttools=4.63.0
  - freetype=2.14.1
  - frozendict=2.4.7
  - frozenlist=1.8.0
  - fsspec=2026.4.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.3.0
  - gitdb=4.0.12
  - gitpython=3.1.50
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.2
  - graphite2=1.3.15
  - greenlet=3.3.2
  - h11=0.16.0
  - h5py=3.16.0
  - harfbuzz=12.3.0
  - hdf5=2.0.0
  - heapdict=1.0.1
  - holoviews=1.23.1
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - hvplot=0.12.2
  - icu=78.3
  - idna=3.18
  - imageio=2.37.3
  - imagesize=1.4.1
  - imbalanced-learn=0.14.2
  - importlib-metadata=8.7.1
  - inflection=0.5.1
  - iniconfig=2.3.0
  - intake=2.0.9
  - intervaltree=3.2.1
  - ipykernel=6.31.0
  - ipympl=0.9.8
  - ipython=9.15.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isort=8.0.1
  - itsdangerous=2.2.0
  - jansson=2.15.0
  - jaraco.classes=3.4.0
  - jaraco.context=6.1.0
  - jaraco.functools=4.4.0
  - jedi=0.19.2
  - jellyfish=1.2.1
  - jinja2=3.1.6
  - jmespath=1.1.0
  - joblib=1.5.3
  - jq=1.8.2
  - json5=0.12.1
  - jsonpatch=1.33
  - jsonpointer=3.1.1
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.9.1
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.1
  - jupyter_server=2.20.0
  - jupyter_server_terminals=0.5.4
  - jupyterlab=4.5.9
  - jupyterlab-variableinspector=3.2.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - keyring=25.7.0
  - kiwisolver=1.4.9
  - krb5=1.22.2
  - lazy_loader=0.5
  - lcms2=2.19.1
  - ld64=956.6
  - lerc=4.1.0
  - libabseil=20260107.0
  - libarchive=3.8.7
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libavif=1.3.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libclang13=22.1.2
  - libcurl=8.21.0
  - libcxx=22.1.2
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.8.2
  - libffi=3.4.8
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libgrpc=1.78.0
  - libhwloc=2.13.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=3.1.3
  - libkrb5=1.22.2
  - liblief=0.17.5
  - libllvm20=20.1.8
  - libllvm22=22.1.2
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libmpdec=4.0.1
  - libnghttp2=1.69.0
  - libopenblas=0.3.31
  - libopenjpeg=2.5.4
  - libopus=1.6.1
  - libpng=1.6.56
  - libpq=17.10
  - libprotobuf=6.33.5
  - libre2-11=2025.11.05
  - libsodium=1.0.21
  - libsolv=0.7.39
  - libspatialindex=2.1.0
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libunistring=1.4.2
  - libuv=1.52.0
  - libvpx=1.16.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.14.6
  - libxslt=1.1.43
  - libzlib=1.3.2
  - linkify-it-py=2.1.0
  - llvm-openmp=22.1.2
  - llvmlite=0.47.0
  - lmdb=0.9.31
  - locket=1.0.0
  - lsprotocol=2025.0.0
  - lxml=6.1.0
  - lz4=4.4.5
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.10.2
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.11.0
  - matplotlib-base=3.11.0
  - matplotlib-inline=0.2.1
  - mbedtls=3.5.1
  - mccabe=0.7.0
  - mdit-py-plugins=0.6.1
  - mdurl=0.1.2
  - menuinst=2.5.2
  - mistune=3.3.3
  - more-itertools=11.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=4.0.3
  - mpich=4.3.2
  - mpmath=1.3.0
  - msgpack-python=1.2.1
  - multidict=6.7.1
  - multipledispatch=1.0.0
  - mypy=1.20.2
  - mypy_extensions=1.1.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - narwhals=2.23.0
  - navigator-updater=0.6.0
  - nbclient=0.11.0
  - nbconvert=7.17.1
  - nbconvert-core=7.17.1
  - nbconvert-pandoc=7.17.1
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - nh3=0.3.2
  - nlohmann_json=3.11.2
  - nltk=3.10.0
  - notebook=7.5.7
  - notebook-shim=0.2.4
  - numba=0.65.1
  - numexpr=2.14.1
  - numpy=2.4.6
  - numpy-base=2.4.6
  - numpydoc=1.10.0
  - oniguruma=6.9.10
  - openldap=2.6.12
  - openpyxl=3.1.5
  - openssl=3.5.7
  - orc=2.2.0
  - packaging=26.0
  - pandas=3.0.3
  - pandoc=3.8
  - pandocfilters=1.5.1
  - panel=1.9.3
  - panel-core=1.9.3
  - panel-material-ui=0.14.0
  - param=2.4.1
  - parso=0.8.7
  - partd=1.4.2
  - patch=2.8
  - pathspec=1.0.4
  - patsy=1.0.2
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=12.3.0
  - pip=26.1.2
  - pixman=0.46.4
  - pkce=1.0.3
  - pkginfo=1.12.1.2
  - platformdirs=4.9.4
  - plotly=6.7.0
  - pluggy=1.6.0
  - prometheus_client=0.24.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.4.1
  - protobuf=6.33.5
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - py-lief=0.17.5
  - py-rattler=0.25.0
  - py-rattler-build=0.65.1
  - pyarrow=23.0.1
  - pybind11-abi=5
  - pycares=4.10.0
  - pycodestyle=2.12.1
  - pycosat=0.6.6
  - pycparser=3.0
  - pyct=0.6.0
  - pydantic=2.13.4
  - pydantic-core=2.46.4
  - pydantic-settings=2.14.2
  - pydocstyle=6.3.0
  - pyerfa=2.0.1.5
  - pyflakes=3.2.0
  - pygithub=2.9.1
  - pygments=2.20.0
  - pyjwt=2.13.0
  - pylint=4.0.6
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.6.2
  - pyobjc-core=12.1
  - pyobjc-framework-cocoa=12.1
  - pyobjc-framework-coreservices=12.1
  - pyobjc-framework-fsevents=12.1
  - pyodbc=5.3.0
  - pyparsing=3.2.5
  - pyproject_hooks=1.2.0
  - pyqt=6.11.0
  - pyqt6-sip=13.11.1
  - pyqtwebengine=6.11.0
  - pyside6=6.11.0
  - pysocks=1.7.1
  - pytables=3.11.1
  - pytest=9.0.3
  - python=3.13.9
  - python-build=1.3.0
  - python-dateutil=2.9.0post0
  - python-dotenv=1.2.1
  - python-fastjsonschema=2.21.2
  - python-installer=1.0.1
  - python-json-logger=4.0.0
  - python-libarchive-c=5.3
  - python-librt=0.8.1
  - python-lmdb=1.7.5
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-ruff=2.3.0
  - python-lsp-server=1.14.0
  - python-multipart=0.0.32
  - python-slugify=8.0.4
  - python-tzdata=2026.2
  - python.app=3
  - python_abi=3.13
  - pytokens=0.4.1
  - pytoolconfig=1.3.1
  - pytz=2026.2
  - pyuca=1.2
  - pyviz_comms=3.0.6
  - pywavelets=1.9.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qdarkstyle=3.2.3
  - qstylizer=0.2.4
  - qtawesome=1.4.2
  - qtbase=6.11.0
  - qtconsole=5.7.2
  - qtdeclarative=6.11.0
  - qtpy=2.4.3
  - qtshadertools=6.11.0
  - qtsvg=6.11.0
  - qttools=6.11.0
  - qtwebchannel=6.11.0
  - qtwebengine=6.11.0
  - qtwebsockets=6.11.0
  - rattler-build=0.55.1
  - re2=2025.11.05
  - readchar=4.2.2
  - readline=8.3
  - referencing=0.37.0
  - regex=2026.5.9
  - reproc=14.2.7
  - reproc-cpp=14.2.7
  - requests=2.34.2
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=15.0.0
  - roman-numerals=3.1.0
  - rope=1.14.0
  - rpds-py=0.28.0
  - rtree=1.4.1
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - ruff=0.15.1
  - s3fs=2026.4.0
  - scikit-image=0.26.0
  - scikit-learn=1.9.0
  - scipy=1.18.0
  - seaborn=0.13.2
  - semver=3.0.4
  - send2trash=1.8.3
  - setuptools=83.0.0
  - shellingham=1.5.4
  - simdjson=3.10.1
  - sip=6.15.1
  - six=1.17.0
  - sklearn-compat=0.1.6
  - smmap=4.0.0
  - snappy=1.2.2
  - snowballstemmer=3.1.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8.4
  - sphinx=9.1.0
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=2.0.0
  - spirv-tools=2026.1
  - spyder=6.1.5
  - spyder-kernels=3.1.5
  - sqlalchemy=2.0.51
  - sqlite=3.53.2
  - stack_data=0.6.3
  - starlette=1.3.1
  - statsmodels=0.14.6
  - streamlit=1.58.0
  - superqt=0.8.1
  - sympy=1.14.0
  - tabulate=0.10.0
  - tapi=1100.0.11
  - tbb=2023.0.0
  - tblib=3.2.2
  - tenacity=9.1.4
  - terminado=0.18.1
  - text-unidecode=1.3
  - textdistance=4.6.3
  - threadpoolctl=3.5.0
  - three-merge=0.1.1
  - tifffile=2026.6.1
  - tinycss2=1.5.1
  - tk=8.6.15
  - toml=0.10.2
  - tomli=2.4.0
  - tomli-w=1.2.0
  - tomlkit=0.15.1
  - toolz=1.1.0
  - tornado=6.5.7
  - tqdm=4.68.2
  - traitlets=5.15.0
  - truststore=0.10.4
  - typer=0.25.1
  - typing-extensions=4.16.0
  - typing-inspection=0.4.2
  - typing_extensions=4.16.0
  - tzdata=2026c
  - uc-micro-py=2.0.0
  - ujson=5.13.0
  - unearth=0.18.2
  - unixodbc=2.3.14
  - urllib3=2.7.0
  - utf8proc=2.11.3
  - uvicorn=0.40.0
  - uvloop=0.22.1
  - watchdog=6.0.0
  - wcwidth=0.8.2
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=16.0
  - werkzeug=3.1.6
  - whatthepatch=1.0.7
  - wheel=0.47.0
  - widgetsnbextension=4.0.14
  - wrapt=2.2.1
  - wurlitzer=3.1.1
  - xarray=2026.7.0
  - xlwings=0.36.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2026.3.0
  - xz=5.8.2
  - yaml=0.2.5
  - yaml-cpp=0.9.0
  - yapf=0.43.0
  - yarl=1.24.2
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.2
  - zlib-ng=2.0.7
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - fastapi==0.136.1
      - ifaddr==0.2.0
      - rangehttpserver==1.4.0
      - soco==0.31.0
      - soco-cli==0.4.86
      - xmltodict==1.0.4
