
# tap repositories and their packages

tap homebrew/core
brew abseil
brew ack
brew aliyun-cli
brew aria2
brew asciidoctor
brew asdf
brew awscli
brew azure-cli
brew bash
brew bat
brew bitwarden-cli
brew bottom
brew buf
brew cabextract
brew cdrtools
brew cmake
brew coreutils
brew curl
brew d2
brew difftastic
brew direnv
brew duckdb
brew etcd
brew eza
brew fd
brew fdupes
brew ffmpeg
brew fish
brew fzf
brew gcc
brew gemini-cli
brew genact
brew gh
brew git
brew git-delta
brew git-lfs
brew gitui
brew gnupg
brew gnuplot
brew gnuradio
brew go
brew golangci-lint
brew gping
brew graphviz
brew grpc
brew helix
brew hidapi
brew htop
brew httpie
brew hyperfine
brew jj
brew jq
brew just
brew lazygit
brew libgccjit
brew librsvg
brew libyaml
brew lnav
brew lua
brew luarocks
brew mas
brew minicom
brew mono-libgdiplus
brew mysql
brew neovim
brew nushell
brew oath-toolkit
brew openssl@3
brew pandoc
brew pdftohtml
brew pinentry-mac
brew pkgconf
brew plantuml
brew podman
brew postgresql@18
brew procs
brew protobuf
brew protoc-gen-go
brew protoc-gen-go-grpc
brew python-yq
brew python@3.13
brew qrencode
brew reattach-to-user-namespace
brew rename
brew ripgrep
brew rsync
brew shellcheck
brew shodan
brew soapysdr
brew starship
brew step
brew stow
brew task
brew tasksh
brew tealdeer
brew terminal-notifier
brew the_silver_searcher
brew thefuck
brew tmux
brew tree
brew typst
brew ufbt
brew unixodbc
brew uv
brew vim
brew wget
brew wimlib
brew zellij
brew zig
brew zoxide
brew zsh
brew zstd

tap homebrew/cask
cask anaconda
cask basictex
cask calibre
cask claude-code
cask font-droid-sans-mono-nerd-font
cask font-hack-nerd-font
cask font-source-code-pro
cask font-source-han-sans-vf
cask font-source-han-serif-vf
cask git-credential-manager
cask gpg-suite
cask gqrx
cask hammerspoon
cask hex-fiend
cask imhex
cask jordanbaird-ice
cask keycastr
cask macfuse
cask netlogo
cask only-switch
cask openrefine
cask powershell
cask quarto
cask r-app
cask responsively
cask rstudio
cask tex-live-utility
cask tor-browser
cask tunnelblick
cask utm
cask vlc
cask warp
cask wave
cask zed

tap buo/cask-upgrade

tap d12frosted/emacs-plus

tap gbevin/tools
brew receivemidi
cask showmidi

tap helix-editor/helix

tap kong/kong

tap leoafarias/fvm

tap microsoft/mssql-release
brew msodbcsql18
brew mssql-tools18

tap modularml/packages

tap openresty/brew

tap rcmdnk/file
brew brew-file

tap xo/xo

# App Store applications
appstore 1659667937 Actions For Obsidian (2025.2.2)
appstore 1586435171 Actions (3.8.0)
appstore 6449173707 Aliworkbench (9.60.03)
appstore 1037126344 Apple Configurator (2.19)
appstore 547166701 BaiduNetdisk (8.1.7)
appstore 1548711022 Barbee (4.1.2)
appstore 1352778147 Bitwarden (2025.12.0)
appstore 1509085044 Bluetooth Inspector (1.6.1)
appstore 640199958 Developer (10.8.3)
appstore 1588151344 Essentials (1.6.2)
appstore 1615988943 Folder Peek (1.12.0)
appstore 682658836 GarageBand (10.4.13)
appstore 1504416652 GeoGebra Calculator Suite (6.0.909)
appstore 6743048714 Googly Eyes (1.1.4)
appstore 1474276998 HP (20.2)
appstore 408981434 iMovie (10.4.3)
appstore 409183694 Keynote (14.4)
appstore 1449106995 NCalc (3.4.9)
appstore 944848654 NeteaseMusic (3.1.3)
appstore 409203825 Numbers (14.4)
appstore 6720708363 Obsidian Web Clipper (0.12.0)
appstore 409201541 Pages (14.4)
appstore 1444636541 Photomator (3.4.12)
appstore 1545810067 Prodrafts (4.3.8)
appstore 1231336508 QQLive (2.151.0)
appstore 595615424 QQMusic (11.0.0)
appstore 409907375 Remote Desktop (3.10)
appstore 1446785996 Scratch 3 (3.31.1)
appstore 1522267256 Shareful (1.11.0)
appstore 897118787 Shazam (2.11.0)
appstore 1496833156 Swift Playground (4.6.4)
appstore 1527036273 Taio (1.68.0)
appstore 899247664 TestFlight (4.1.0)
appstore 497799835 Xcode (26.2)
appstore 1247341465 同花顺 (5.2.2)
appstore 1640407382 抖音 (6.9.0)
appstore 491854842 网易有道翻译 (11.2.13)

# Main file
main ./Brewfile.$HOSTNAME
